USE [VOICE_CONTROLLED_PARKINGFACILITY]

DROP TABLE IF EXISTS[BESTUURDER]
DROP TABLE IF EXISTS[AUTO]
DROP TABLE IF EXISTS[HISTORY]
DROP TABLE IF EXISTS[BILLING]
DROP TABLE IF EXISTS[LOCATION]

CREATE TABLE [USER] (
	Name VARCHAR(10) PRIMARY KEY

)

CREATE TABLE [CAR] (
	License_plate VARCHAR(10) PRIMARY KEY
,	FK_Name VARCHAR(10)

	CONSTRAINT FK_NAME FOREIGN KEY (FK_NAME) REFERENCES [USER](Name)
)

CREATE TABLE [HISTORY] (
	ID INT PRIMARY KEY
,	FK_Name VARCHAR(10)
,	FK_License_plate VARCHAR(10)

	CONSTRAINT FK_NAME FOREIGN KEY (FK_NAME) REFERENCES [USER](Name)
)