USE [VOICE_CONTROLLED_PARKINGFACILITY]

DROP TABLE IF EXISTS[BESTUURDER]
DROP TABLE IF EXISTS[AUTO]
DROP TABLE IF EXISTS[PARKEERLOCATIE]
DROP TABLE IF EXISTS[REGISTRATIE_RECORD]

CREATE TABLE [USER] (
	Naam VARCHAR(10) PRIMARY KEY

)

CREATE TABLE [AUTO] (
	Kenteken VARCHAR(10) PRIMARY KEY
,	FK_Naam VARCHAR(10)

	CONSTRAINT FK_Naam FOREIGN KEY (FK_Naam) REFERENCES [USER](Naam)
)

CREATE TABLE [REGISTRATIE_RECORD] (
	ID INT PRIMARY KEY
,	FK_Naam VARCHAR(10)
,	FK_Kenteken VARCHAR(10)

	CONSTRAINT FK_Naam FOREIGN KEY (FK_Naam) REFERENCES [USER](Naam)
)